### PR TITLE
Added cve.py module to search my NVD database web app for CVE info.

### PR DESCRIPTION
**Pull request by plasticuproject**
Returns CVE IDs based on search or details based on supplied ID.
```
Search CVE records by ID, YEAR and/or KEYWORD. Prints ID and description only.

USAGE:
$cve <CVE-ID>
$cve <year> (keyword)
$cve all (keyword)
$cve recent (keyword)
$cve modified (keyword)
```

### CODE REVIEW

**Comment by plasticuproject** [comment]
@ethanizen Would you mind testing this out? I spammed it with what I could think of without errors. Just be careful if you use the `all` command, my web api that this is pulling from is really just a beta and is not scaled, and `all` processes a lot of data.

**Comment by ethanizen** [comment]
I'll take a look at it and run some tests in a bit, but from an organizational aspect the show_help variable should become a class member so it can be accessed using CVE.show_help from anywhere that imports CVE. As it stands right now, it can only be called from within the CVE.search() method.

**Comment by ethanizen** [comment]
Also line 67 doesn't need to be there. Once we reach that point, it's guarranteed for len(cves) > 1, because we already did the two previous checks on lines 56 and 60.

**Comment by plasticuproject** [comment]
CVE.search() is the primary function for the module and should be used everytime you use the module. There is no need to access show_help otherwise. Show help is just an error catching device for the search() function.I don't want show_help to be accessed otherwise as the argument number checking is build into the logic of search(). Imagine this was a stand alone file, search() would be the only function, and cveSearch() would be the `if name == '__main__'` function. There's no need to make a second function for it.

Line 67, I prefer explicit checks when possible, it's good form. It's specific expected outcome for a specific expected condition.

**Comment by ethanizen** [comment]
Ok, makes sense. Just ran some tests and I can't seem to find anything wrong with it.

**Pull request merged**
