### PR TITLE
Add `$news` to bot

### PR DESCRIPTION
**Pull request by ethanizen**
This PR adds the ability for `$news` to be called in a channel.

Functionality is as follows:
`$news [site] [number]`
This returns a list of length `number` of articles, published today, from `site`.

This PR also adds the discordhelp.py module, which will hold helpful methods that make interacting with Discord easier.

### CODE REVIEW

**Comment by ethanizen** [comment]
No I don't think we should. We won't be instantiating the News class, as we are only using the methods that it contains, and not running operations on the object. 

If we were to say, hold the articles in a field of an instantiated News object, and then call methods on those objects, then we would use it as a class method. But again, we aren't going to be instantiating the class.

Not sure if that made sense, let me know if I need to clarify anything.

**Comment by plasticuproject** [comment]
There's also some issues with the error handling here. Running `$news bleepingcomputer d` will produce the error:
```
  File "/new_jarvis_discord_bot/modules/news.py", line 126, in getNews
    n = int(split_message[2])
ValueError: invalid literal for int() with base 10: 'd'
```
And I think the error handling on lines 131 to 133 is redundant or not needed.

**Comment by ethanizen** [comment]
Ah yes good catch. I suck at finding bugs. I'll fix that in the morning it's midnight here.

And I'm not sure how it's redundant? That's the only place we check for UnkownSiteError, and that's only ever thrown from `getNewsList()` on line 113.

**Comment by plasticuproject** [comment]
I tried to produce that error but could not. Running: `$news skdjfksdjf` returns 
```
Format is 
$news [website] [number of articles]
```
as a response, with no error.

**Comment by plasticuproject** [comment]
Running `$news bleepingcomputer 100` produces:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/Envs/jarvis/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 30, in on_message
    await message.channel.send(result)
  File "/home/Envs/jarvis/lib/python3.6/site-packages/discord/abc.py", line 856, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/Envs/jarvis/lib/python3.6/site-packages/discord/http.py", line 225, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
```

**Comment by ethanizen** [comment]
Pushed three new commits:

The first two fix the bugs pointed out by @plasticuproject and the last one makes a slight modification to the command format, and also reformats the help message (which will need to be changed because it's ugly right now).

**Comment by plasticuproject** [comment]
Now that we have a working bot function, I'll see if aroe will let me set up automatic deployment on heroku or something.

**Comment by aroesec** [comment]
sweeet

**Pull request merged**
